---
clone:
  depth: 1
kind: pipeline
name: sid 386 build
pull: always
steps:
- commands:
  - echo hello world
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
trigger:
  event:
  - push
  - tag
  - custom
